version: "3.7"


services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      
  zookeeper:
    user: root
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "2181:2181" 
    container_name: zookeeper
    hostname: zookeeper
    volumes:
      - ./data/zookeeper:/tmp/zookeeper  
    environment:
      - KAFKA_HOME=${KAFKA_HOME}
    command: "${KAFKA_HOME}/bin/zookeeper-server-start.sh ${KAFKA_HOME}/config/zookeeper.properties"

  kafka:
    image: docker.io/bitnami/kafka:3.6
    container_name: kafka  
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_HOME=${KAFKA_HOME}
    user: root
    volumes:
      - ./data/kafka_logs:/etc/logs
      - ./config/kafka/server.properties:${KAFKA_HOME}/config/server.properties:ro
    command: ${KAFKA_HOME}/bin/kafka-server-start.sh ${KAFKA_HOME}/config/server.properties

  kafka-connect:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "8083:8083"
    hostname: kafka-connect
    container_name: kafka-connect
    depends_on:
      - kafka
    environment:
      - KAFKA_HOME=${KAFKA_HOME}
    volumes:
      - ./config/kafka/inventory-mysql-kafka-connect.properties:${KAFKA_HOME}/config/inventory-mysql-kafka-connect.properties:ro
      - ./config/kafka/server.properties:${KAFKA_HOME}/config/server.properties:ro
      - ./config/kafka/connect-standalone.properties:${KAFKA_HOME}/config/connect-standalone.properties:ro
      - ./config/kafka/debezium-connector-mysql:${KAFKA_HOME}/libs/debezium-connector-mysql
    command: "${KAFKA_HOME}/bin/connect-standalone.sh ${KAFKA_HOME}/config/connect-standalone.properties ${KAFKA_HOME}/config/inventory-mysql-kafka-connect.properties"

  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8081:8080
  #   environment:
  #     - DYNAMIC_CONFIG_ENABLED='true'
  #     - SPRING_CONFIG_ADDITIONAL-LOCATION=/config.yml
  #     - KAFKA_HOST=${KAFKA_HOST}
  #   volumes:
  #     - ./kui/config.yml:/config.yml:ro

volumes:
  mysql_data:
  broker: