version: '3.7'

services:
  # spark-apps:
  #   user: root
  #   image: spark:latest
  #   container_name: spark-apps
  #   volumes:
  #     - ./config/docker-compose/spark:${SPARK_HOME}/conf/:ro
  #     - ./code:${SPARK_HOME}/code:ro
  #     - spark_home:/home/spark:rw
  #   command: "${SPARK_HOME}/bin/spark-submit 
  #     --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 \ 
  #     --master spark://spark-master:${SPARK_MASTER_PORT} \
  #     --executor-cores 4 \
  #     --executor-memory 8G \
  #     ${SPARK_HOME}/code/process.py"

  spark-master:
    user: root
    image: spark:latest
    container_name: spark-master
    ports:
      - "${SPARK_MASTER_WEB_UI_PORT}:${SPARK_MASTER_WEB_UI_PORT}"
      - "${SPARK_MASTER_PORT}:${SPARK_MASTER_PORT}"
    volumes:
      # - ./config/docker-compose/spark:${SPARK_HOME}/conf/:ro
      - ./code:${SPARK_HOME}/code:ro
      # - spark_home:/home/spark:rw
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:${SPARK_MASTER_WEB_UI_PORT}/"]
      interval: 1s
      timeout: 10s
      retries: 5
    command: bash -c "
      ${SPARK_HOME}/sbin/start-master.sh \
      && tail -f"

  spark-thriftserver:
    image: spark:latest
    container_name: spark-thriftserver
    ports:
      - "4040:4040"
      - "10000:10000"
    depends_on:
      - spark-master:healthy
    volumes:
      # - ./config/docker-compose/spark:${SPARK_HOME}/conf/:ro
      - ./config/docker-compose/spark/spark-thriftserver.properties:${SPARK_HOME}/conf/spark-thriftserver.properties:ro
    command: bash -c "${SPARK_HOME}/sbin/start-thriftserver.sh \
      --master spark://spark-master:${SPARK_MASTER_PORT} \
      --properties-file ${SPARK_HOME}/conf/spark-thriftserver.properties
      && tail -f"

  spark-worker-1:
    image: spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:${SPARK_MASTER_PORT}
    # volumes:
      # - ./config/docker-compose/spark:${SPARK_HOME}/conf/:ro
    command: bash -c "${SPARK_HOME}/sbin/start-worker.sh -m ${SPARK_WORKER_MEM} -c ${SPARK_WORKER_CORES} spark://spark-master:${SPARK_MASTER_PORT} && tail -f"

  spark-worker-2:
    image: spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MASTER=spark://spark-master:${SPARK_MASTER_PORT}
    # volumes: 
      # - ./config/docker-compose/spark:${SPARK_HOME}/conf/:ro
    command: bash -c "${SPARK_HOME}/sbin/start-worker.sh -m ${SPARK_WORKER_MEM} -c ${SPARK_WORKER_CORES} spark://spark-master:${SPARK_MASTER_PORT} && tail -f"

  
volumes:
  spark_home: