kafka:
  clusters:
    -
      name: local
      bootstrapServers: ${KAFKA_HOST}:9092
      # schemaRegistry: http://localhost:8085
      # schemaRegistryAuth:
      #   username: username
      #   password: password
#     schemaNameTemplate: "%s-value"
      metrics:
        port: 8080
        type: JMX